name: Aerosthetics
favicon: null
layout_spectrum: 0.836729328148067
typography_spectrum: 0.508889842312783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.008787124417722225
  lightness: 0.4656182040926069
  saturation: 0.03348030708730221
  rhythmicContrast: 0.8693587225861847
purpose: []
