name: Aerosthetics
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c4c4c4'
    - '#5a595a'
    - '#2c2a2c'
    - '#74ccf4'
  brandStrength: 0
  lightness: 0.4656182040926069
  saturation: 0.03348030708730221
  rhythmicContrast: 0.8693587225861847
purpose: []
